server:
  token: "abc"

transport:
  websocket:
    enabled: true
    ip: "0.0.0.0"
    port: 8000
  grpcgateway:
    browser: true
    enabled: true
    ip: "0.0.0.0"
    port: 50051

log:
  log_format: "{time:YYYY-MM-DD HH:mm:ss} - {level} - {message}"
  log_level: "INFO"
  log_dir: "logs"
  log_file: "im-server.log"